# Generated by Django 3.0.4 on 2020-06-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_imgsrc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='imgSrc',
            new_name='image',
        ),
    ]
