# Generated by Django 3.0.4 on 2020-06-05 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('project', '0005_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('navBarName', models.TextField(max_length=50)),
                ('url', models.TextField(max_length=50)),
                ('subtitle', models.TextField(max_length=100)),
                ('text', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
