# Generated by Django 3.0.4 on 2020-06-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_apppage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppage',
            old_name='url',
            new_name='urlPath',
        ),
    ]
