# Generated by Django 3.0.4 on 2020-06-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200605_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppage',
            old_name='navBarName',
            new_name='slogen',
        ),
    ]
