# Generated by Django 3.0.4 on 2020-06-06 15:12

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_delete_apppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cards',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.TextBlock())], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='aboutPageSubtitle',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='aboutPageText',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='app',
            name='contactPageSubtitle',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='contactPageText',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='app',
            name='homePageSubtitle',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='app',
            name='homePageText',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
