# Generated by Django 3.0.4 on 2020-06-06 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200606_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='cards',
        ),
    ]
