# Generated by Django 3.0.4 on 2020-06-06 16:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_app_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='cards',
            field=wagtail.core.fields.StreamField([('abc', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=40, required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=200, required=True)), ('button_url', wagtail.core.blocks.CharBlock(max_length=40, required=True))])))]))], blank=True, null=True),
        ),
    ]
