# Generated by Django 3.0.4 on 2020-06-07 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('project', '0016_app_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='jumbotron',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
