# Generated by Django 3.0.4 on 2020-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_app_jumbotron'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='github',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='app',
            name='twitter',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
