# Generated by Django 3.0.4 on 2020-06-08 13:19

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20200608_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='aboutPageText',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
