# Generated by Django 3.0.4 on 2020-06-08 14:56

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20200608_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='contactPageText',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='homePageText',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
    ]
